### ISSUE TITLE
Bad npm install command : 'npm i ldCover' => 'npm install ldcover'

### ISSUE THREAD

**Issue by mathieugalle** [loadingio/ldcover#11]
Hi,

I just followed (=copy-pasted) instructions on [your site documentation](https://loading.io/lib/modal/
)
`npm i ldCover`

And I got : 

```
npm i ldCover
npm ERR! code E404

npm ERR! 404 Not Found - GET https://registry.npmjs.org/ldCover - Not found
npm ERR! 404  'ldCover@*' is not in this registry.
npm ERR! 404 This package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
```
The correct command is in the github repo : `npm install ldcover`

This is not a big bug, just slighly annoying and easily fixable if you have some time to do so.
Thank you for this library

**Comment by zbryikt** [comment]
We renamed `ldCover` to `ldcover` some time ago which also affects all examples shown in the documentation so actually there are a lot to patch; unfortunately in the documentation page we still use the old version of ldCover so it's kinda a mess and that's the reason why we didn't update the document along with the revision of this library.

We are working on a service upgrade and have prepared a new document for the latest version (3.5.3) along with the service update, so the old document will be updated after we deploy. :)

While the document on loading.io is not updated, README here is always up to date so for any information inconsistency please consider README here as the correct one. :)

**Comment by zbryikt** [comment]
We have updated our online document so will close this issue as finished.
